## [admin]
### POST admin/register-admin [register]
POST http://127.0.0.1:8037/admin/register-admin
Content-Type: application/json

{
  "firstname": " ",
  "lastname": " ",
  "email": " ",
  "password": " "
}

### POST admin/login [login]
POST http://127.0.0.1:8037/admin/login
Content-Type: application/json

{
  "email": " ",
  "password": " ",
  "rememberMe": false
}

### status code 204 is pass
### POST admin/forgot-password [forgot password]
POST http://127.0.0.1:8037/admin/forgot-password
Content-Type: application/json

{
  "email": " "
}

### POST admin/reset-password [reset password]
POST http://127.0.0.1:8037/admin/reset-password
Content-Type: application/json

{
  "password": " ",
  "resetPasswordToken": " "
}

### GET admin/users/me [profile & role] use token
GET http://127.0.0.1:8037/admin/users/me
Authorization: Bearer {{Token-JWT}}

##=======================================================##

## user/customer

###POST api/auth/local [login]
POST http://127.0.0.1:8037/api/auth/local
Content-Type: application/json

{
  "identifier": " ",
  "password": " "
}

### POST api/auth/local/register [register]
POST http://127.0.0.1:8037/api/auth/local/register
Content-Type: application/json

{
  "username" : " ",
  "email" : " ",
  "password" : " "
}

### POST api/auth/forgot-password [forgot password]
POST http://127.0.0.1:8037/api/auth/forgot-password
Content-Type: application/json

{
  "email" : " "
}

### POST api/auth/reset-password [reset password]
POST http://127.0.0.1:8037/api/auth/reset-password
Content-Type: application/json

{
  "code" : " ",
  "password" : " ",
  "passwordConfirmation" : " "
}

### GET api/users/me [get profile]
GET http://127.0.0.1:8037/api/users/me
Authorization: Bearer {{Token-JWT}}
